### ISSUE TITLE
setjmp/longjmp not exposed if -D_BSD_SOURCE (or -D_GNU_SOURCE) is used with -ansi

### ISSUE THREAD

**Issue by csnover** [freemint/mintlib#27] opened 2017-11-05 03:24 UTC
This condition happens with ScummVM which currently assumes that any compiler with `__GNUC__` defined will also have the non-standard `strdup`. This is probably a defect in ScummVM, but this seems to be a known condition as there is [already a bug-marker in the source](https://github.com/freemint/mintlib/blame/master/include/setjmp.h#L23) about it. I am not familiar with the requirements here; is there any reason why the `#ifdef` on 39 can’t simply be changed to `#if !defined(__USE_BSD) || defined(__STRICT_ANSI__)`? Making this change allows ScummVM to compile successfully.

**Comment by th-otto** [comment] 2017-11-05 04:02
I think this is not a bug. You will get the same result when using recent glibc on linux. By specifying -ansi you declare that you won't be using non-standard functions like setjmp. Same for strdup().

**Comment by csnover** [comment] 2017-11-05 04:17
setjmp does not appear to be non-standard; it is defined in C89 §4.6.1 and C99/11 §7.13. Could you explain more, so I understand?

(I don’t know why `-ansi` is even being used. Much of the ScummVM build system is archaic and full of magic like this, which I hope will eventually get cleared up over time.)

**Comment by th-otto** [comment] 2017-11-05 04:35
Maybe the function is defined there, but the semantics in Posix have changed, where sigsetjmp should be used instead. Glibc tries to support both, depending on the feature macros, and mintlib was once derived from it. Maybe the tests are now somewhat broken, but using -ansi in general does not work very well when you wan't to use posix features. I think removing -ansi from the flags, or specifying _GNU_SOURCE for the offending sources should do the trick in your case.

**Comment by csnover** [comment] 2017-11-05 04:57
Thanks for the additional information regarding POSIX conventions!

Getting rid of `-ansi` whilst continuing to use `_GNU_SOURCE` addresses the compilation trouble on this side, so unless you want to hold this ticket open until the `/* BUG */` is gone, or decide to expose `setjmp`/`longjmp` (which would match GLib 2.50, at least, it seems), please feel free to close this any time.

**Comment by mikrosk** [comment] 2018-05-20 06:10
Hasn't this been fixed by https://github.com/freemint/mintlib/commit/68dd1979ea213a0cebec18bc34ff7db250656213 ?

**Closed** 2018-07-13 14:13 UTC
